Ingestor wallet.coinbase
floornfts/mobile-minting pull request #34
Opened 2024-07-30 17:05 UTC by pbkompasz

## Mint Ingestor: [Coinbase Wallet](https://wallet.coinbase.com/) (#11)

### Functionality Supported
* Ingesting from URL: Yes
* Ingesting from Contract address: Yes
* Supported Networks: Base

### Before you submit
- [X] Ensure your generated MintTemplate works 😄
- [X] Ensure that your code is restricted to a single folder in `src/ingestors`
- [X] Ensure that all required assets are included (e.g. ABIs)
- [X] Ensure ABIs are trimmed to include only methods (1) used in the ingestor or (2) required to mint
- [X] Ensure that all exported methods are prefixed with the name of your ingestor e.g. `myMintingPlatformGetContractDetails`
- [X] Ensure that a test exists for generating a MintTemplate that will always succeed
- [X] Ensure that your code accesses **no external resources** except those passed in the `resources` object

2024-08-09 18:51 UTC, agans commented on src/ingestors/coinbase-wallet/index.ts
> +      .setPartnerName('Highlight');
hi! Looks like there are a couple highlight references in here

2024-08-12 10:01 UTC, pbkompasz commented
@agans I removed the Highlight references and I also had to rewrite to fetch the collection metadata from the blockchain.

2024-08-22 20:34 UTC, pbkompasz commented
@chrismaddern This is also ready for review.

2024-08-26 20:27 UTC, chrismaddern commented
Will be reviewing this shortly (probably tomorrow vs. today)

Apologies for the delay. The typical review is not quick and most have led to rejections / changes so most are reviewed multiple times. Having to spread them out!! 🙏 🙏 🙏 🙏

2024-08-26 20:43 UTC, chrismaddern commented
Hi @pbkompasz I pulled these to run tests locally before finalizing for merge.

I'm seeing one failure:
![CleanShot 2024-08-26 at 16 42 15@2x](https://github.com/user-attachments/assets/87bc5c5a-2dfc-4895-b0e8-bbd3b5fa80b8)

Could you take a look and get it passing?

It may be related to the fact that your `basicIngestorTests` aren't providing a static blockhash to simulate at - here's an example, and looks like you'll need to pull a blockhash from a couple weeks ago when you made this for it to work reliably moving forward.

e.g.
https://github.com/floornfts/mobile-minting/blob/main/test/ingestors/rodeo.test.ts#L30

2024-08-26 20:44 UTC, chrismaddern requested changes
Dropped a comment with changes at the top. Excited to get it across the line

2024-08-28 15:03 UTC, chrismaddern approved these changes

2024-08-28 15:03 UTC, chrismaddern commented
/review

2024-08-28 15:03 UTC, chrismaddern commented
> There might be some bug in the basicIngestorTests, because the simulation did fail in dry run but passed in basicIngestorTests.

I think it's because basicIngestorTests is using the blockhash provided, but dry-run is using the latest block hash?

Tests pass for me. Doing final review for merge! 🙂

2024-08-28 15:06 UTC, merged